'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bitacora
    Public Property IdBit As Integer
    Public Property IdUsuario As Integer
    Public Property Accion As String
    Public Property FechaModificacion As Date
    Public Property IdCliente As Integer
    Public Property NombreUsuario As String

    Public Overridable Property Usuario As Usuario

End Class
