'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property IdUsuario As Integer
    Public Property NombreUsuario As String
    Public Property Contrasena As String

    Public Overridable Property Bitacora As ICollection(Of Bitacora) = New HashSet(Of Bitacora)

End Class
